# Site settings
title: James Bird
description: > # this means to ignore newlines until "baseurl:"
  I am a software developer with a focus on computer graphics and animation.
  I currently work at Playground Games as a Principal Animation Engineer. Prior to this, 
  I've held a number of positions in the games and film (visual effects) industries. This 
  is my personal blog and does not represent the views of my employers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jbrd.github.io/" # the base hostname & protocol for your site
twitter_username: bird_james
github_username:  jbrd
exclude: ["Gemfile","Gemfile.lock","README.md","vendor"]

# Build settings
markdown: kramdown

# Dependencies
plugins:
  - jekyll-gist
mathjax_path: "https://cdn.mathjax.org/mathjax/latest/MathJax.js"
mathjax_config: "?config=TeX-AMS-MML_HTMLorMML"
