# Site settings
title: James Bird
description: > # this means to ignore newlines until "baseurl:"
  I am a lead software developer in the visual effects industry. I currently
  work at DNEG, where I lead Virtual Production R&D. Prior to this, I worked
  at a variety of software and game studios (Microsoft - Lift/Rare, Realtime 
  Worlds, eeGeo). This is my personal blog and does not represent the views 
  of my employers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jbrd.github.io/" # the base hostname & protocol for your site
twitter_username: bird_james
github_username:  jbrd
exclude: ["Gemfile","Gemfile.lock","README.md","vendor"]

# Build settings
markdown: kramdown

# Dependencies
gems:
  - jekyll-gist
mathjax_path: "https://cdn.mathjax.org/mathjax/latest/MathJax.js"
mathjax_config: "?config=TeX-AMS-MML_HTMLorMML"
