# Site settings
title: James Bird
description: > # this means to ignore newlines until "baseurl:"
  I am a programmer with an interest in computer graphics and animation.
  I have worked in the computer games and visual effects industries, and
  currently work at Microsoft as a Senior Software Engineer. This is my
  personal blog and does not represent the views of my employers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jbrd.github.io/" # the base hostname & protocol for your site
twitter_username: bird_james
github_username:  jbrd
exclude: ["Gemfile","Gemfile.lock","README.md","vendor"]

# Build settings
markdown: kramdown

# Dependencies
gems:
  - jekyll-gist
mathjax_path: "http://cdn.mathjax.org/mathjax/latest/MathJax.js"
mathjax_config: "?config=TeX-AMS-MML_HTMLorMML"
